### ISSUE TITLE
ElasticSearch container dies when SELF_MONITORING_ENABLED is commented (as delivered in env-sample Community version)

### ISSUE THREAD

**Issue by rribei** [Axway-API-Management-Plus/apigateway-openlogging-elk#151]
Attempts to run the command "docker-compose --env-file ./.env -f elasticsearch/docker-compose.es01.yml -f elasticsearch/docker-compose.es01init.yml up -d" (instructions from Basic Setup -> Setup Elasticsearch), results in a warning message as below and ElasticSearch container dies quickly.  

WARNING: The SELF_MONITORING_ENABLED variable is not set. Defaulting to a blank string.

The issue was solved by uncommenting SELF_MONITORING_ENABLED from .env

Is it possible to deliver the env-sample uncommented by default?

**Comment by cwiechmann** [comment]
Hi @rribei, the Warning-Log message is expected and not causing Elasticsearch to fail. Perhaps, this is some kind of duplicate to issue #152? 

Closing this now. Feel free to re-open if you need more information.
