### ISSUE TITLE
Value for ES_JAVA_OPTS when using the Basic Setup of 3.6.0

### ISSUE THREAD

**Issue by rribei** [Axway-API-Management-Plus/apigateway-openlogging-elk#152]
**Axway APIM-ELK version**
v3.6.0

**API-Manager Version**
7.7.20210830

**Actual behavior**

Following the instructions from Basic Setup -> Setup ElasticSearch and setting the ES_JAVA_OPTS with "-Xms8g -Xmx8g" or "-Xms5g -Xmx5g" resulted in ElasticSearch startup failure as below:

ERROR: [1] bootstrap checks failed. You must address the points described in the following [1] lines before starting Elasticsearch.
bootstrap check failure [1] of [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/demo-elasticsearch.log

**Expected behavior**
Provide a sample value that doesn't cause this issue. I tried again with "-Xms512m -Xmx512m" and it didn't cause the issue.

**Comment by cwiechmann** [comment]
Thanks for reporting @rribei. However, this is more related to the OS system and of course it makes no real sense to start Elasticsearch with 512MB only.

Please check the following:
https://stackoverflow.com/questions/51445846/elasticsearch-max-virtual-memory-areas-vm-max-map-count-65530-is-too-low-inc

However, it makes sense to document this.
