### ISSUE TITLE
docker-compose and .env in README

### ISSUE THREAD

**Issue by cbrowet-axway** [Axway-API-Management-Plus/apigateway-openlogging-elk#159]
I see the note regarding .env and docker-compose in the README, but I'm using version v2.2.2 and the different behavior is still there, so meant to stay, I think.

As such, for any `docker-compose -f ...` in a subdirectory, I have to do `docker-compose --env-file .env -f ...`

**Comment by cwiechmann** [comment]
Yes, I agree it makes sense to avoid this issue/confusion.

**Comment by cwiechmann** [comment]
Thanks for reporting this @cbrowet-axway. I changed this right away, as you suggested to get it out of the way.
