### ISSUE TITLE
Transactions from scheduled policies show up in traffic monitor as undefined

### ISSUE THREAD

**Issue by jojo221119** [Axway-API-Management-Plus/apigateway-openlogging-elk#19]
If a scheduled policies uses the "Connect to URL" filter those transactions show up in traffic monitor as undefined.

My suggestion is to either check whether there is data available to make those requests showing up the same way as the normal requests would.

Or to prevent them from being ingested into Elastic search in the first place. Find attached a Logstash pipeline which achieves this.
[pipeline.txt](https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/files/5021703/pipeline.txt)

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @jojo221119. Do you think in general it is worth to have this kind of information in ES? Perhaps in a different index instead of skipping in completely?

**Comment by jojo221119** [comment]
I think it makes sense to have them in ES as it could be valuable during troubleshooting of the policies.

**Comment by cwiechmann** [comment]
Support for Scheduled-Polices has been added and will be shown like so:
![image](https://user-images.githubusercontent.com/16292002/91070908-c28f9180-e637-11ea-82c4-465118a3a541.png)
Such documents are inserted into a separate index: `apigw-traffic-scheduled-%{+YYYY.MM.dd}` to get more flexibility. For instance delete this information every day. 
Unfortunately the current event doesn't contain much information.
