### ISSUE TITLE
Data Monitoring Not Show Up

### ISSUE THREAD

**Issue by aditya40** [Axway-API-Management-Plus/apigateway-openlogging-elk#221]
### ELK-Solution version

4.1.0

### Elastic-Stack version

7.17.0

### API-Management version

7.7.0.20211130

### Number of APIs

1

### Number of Applications

1

### Number of Transactions

5

### API-Management deployment option

Classic VMs

### ELK-Solution deployment option

Classic VMs using Docker-Compose

### Bug description

HI

I have prepared all the configs that need to be integrated between ELK and Axway 7.7.0.20211130,
But when I import *.ndjson only [Axway] API-Management KPIs data appears in ELK,
while other data such as [Axway] API-Requests Quarterly, [Axway] API-Requests Real-Time, [Axway] API-Requests Yearly,
[Axway] Domain Audit not showing up,
I've provided a screenshot for reference

Regards
Aditya 

![Axway  API-Management KPIs](https://user-images.githubusercontent.com/58604981/184849475-b3f7e30e-78c2-4a0d-a9e7-ce87237c51ee.png)
![Axway  API-Requests Quarterly](https://user-images.githubusercontent.com/58604981/184849509-27ba5fa8-7516-4d75-9ce5-39a9e7a8c976.png)
![Axway  API-Requests Real-Time](https://user-images.githubusercontent.com/58604981/184849532-07f79c6f-45bb-47c4-b108-32421cecf03a.png)
![NDJSON](https://user-images.githubusercontent.com/58604981/184849563-69cae822-36a7-4273-a3b2-f2abdbdd1d81.png)

**Comment by NComandini** [comment]
Hi @aditya40,

As all data aren't reported, I suspect a problem with the filebeat component.
Could you verify and post the filebeat logs please ?

**Comment by aditya40** [comment]
this is the log result from filebeat, 
![filebeat](https://user-images.githubusercontent.com/58604981/185331019-4d2e1e4d-e6ee-4bd6-bebd-98eb4d23c32c.png)

**Comment by aditya40** [comment]
and this is file logs from filebeat

[filebeat-json.log](https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/files/9371883/filebeat-json.log)

**Comment by NComandini** [comment]
The certificate message isn't the problem.
Filebeat can't connect to the Logstash component : 
`{"log":"2022-08-05T14:25:58.727+0700\u0009ERROR\u0009[publisher_pipeline_output]\u0009pipeline/output.go:154\u0009Failed to connect to backoff(async(tcp://[https://192.168.37.137:5044]:5044)): lookup https://192.168.37.137:5044: no such host\n","stream":"stderr","time":"2022-08-05T07:25:58.727798557Z"}
`
Please verify that Logstash is up and running, the IP is good and the port is open on this VM.

**Comment by aditya40** [comment]
Sorry @NComandini for slow respon
this is log in logstash and docker container status

![logstash log](https://user-images.githubusercontent.com/58604981/185880117-33b58eba-fa98-4b45-9583-40200ea923f9.png)

![docker status](https://user-images.githubusercontent.com/58604981/185880711-e4f10561-0acf-41ba-8bed-3bec3b2342e2.png)

**Comment by aditya40** [comment]
hi @NComandini can you help me with this issue.?

**Comment by NComandini** [comment]
Hi @aditya40,
I apologize for the late answer.
I'm surprise about your problem, the api-builder is up. It means that the connexion is good.
Could you check that some data are available on Kibana  :

- Click on the menu
- Select "Discover" in "Analytics" section
- Select the index Pattern "apigw-index-summary*"

You must see some logs in the main frame.

By checking a new time your log, I see that you are using IP addresse. 
Could you change them by DNS host name ?
If you are using the docker compose, you must add a DNS host resolution (that's not possible with our file by default).
Edit the docker-compose.yaml file and add the following line in apibuilder4elastic section (if you are using the name api-env) : 
```
  apibuilder4elastic:
  …
    extra_hosts:
        - "api-env.demo.axway.com:XXX.XXX.XXX.XXX" #host and ip to resolve the api-manager host
```

Also be sure that the DNS resolution is appropriate on your /etc/hosts for others components.
By default, you must add that : 
```
XXX.XXX.XXX.XXX elasticsearch1 apibuilder4elastic
```

**Comment by NComandini** [comment]
I close it without update.
Please open a ticket to the Axway support if the problem persist.
