### ISSUE TITLE
Add reporting capability in Kibana

### ISSUE THREAD

**Issue by axway-akb** [Axway-API-Management-Plus/apigateway-openlogging-elk#223]
### Feature request

It would be great to have reporting capability in Kibana so that generated reports can be shared to stakeholders outside the technical/operations teams. 

For example, reporting requirement in open banking UK are following:
https://standards.openbanking.org.uk/operational-guidelines/availability-and-performance/latest/

The template for reporting (for financial institutions) can be downloaded from https://standards.openbanking.org.uk/operational-guidelines/availability-and-performance/publication-of-statistics/latest/#ASPSP-reporting-template

**Comment by NComandini** [comment]
I've added your requirement in [AmplifyIdea ](https://amplifyideas.axway.com/ideas/AMPANA-I-11)

This repository is going to be archived because Axway provides an official distribution.
Please use the Axway channels.
