### ISSUE TITLE
Default policy Protect Management Interfaces not available

### ISSUE THREAD

**Issue by sebastianwaclawski** [Axway-API-Management-Plus/apigateway-openlogging-elk#230]
### ELK-Solution version

4.2.0

### Elastic-Stack version

7.17.0

### API-Management version

7.7.20211130

### API-Management deployment option

Classic VMs

### Question

Where and how to implement policy from **nodemanager/policy-use-elasticsearch-api-7.7.0.xml** if the default **Protect Management Interfaces** is not available?

**Comment by NComandini** [comment]
The policy "Protect Management Interfaces" is embbeded  in the FED of the **node manager** on all API Manager version.
This FED is not the same wihich you push the api-manager settings and API policies. 
It isn't possible to create an ANM FED from the policy studio and the best way is to open an existing project:

- Extract the folder on your Admin Node Manager VM : <install path>/apigateway/conf/fed/
- Open the policy studio
- Create a new api-project from existing configuration
- Select the extracted folder
- You must see the following configuration :

![image](https://user-images.githubusercontent.com/28092073/193232439-76b16a2b-0822-4fe2-83f4-4e6d8892e6a7.png)

**Comment by NComandini** [comment]
I close this issue without update.

Please open an Axway support request for additional questions.
