### ISSUE TITLE
2-way TLS in filebeat to logstasch connection

### ISSUE THREAD

**Issue by sebastianwaclawski** [Axway-API-Management-Plus/apigateway-openlogging-elk#231]
### Problem description

Currently there is no support for 2-way TLS connection in filbeat to logstash connection.
This  is officially support in filebeat->logstash.
Documentation - https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html

### Feature request

Please introduce 2-way TLS in filebeat to logstash connection.

**Comment by NComandini** [comment]
I've checked and this feature is compatible with version 7.17.
Our R&D is working on a new release.

I've added it in our portal Amplify Ideas to add it in the official backlog : https://amplifyideas.axway.com/ideas/AMPANA-I-5
