### ISSUE TITLE
Prerequisites - compatibility matrix

### ISSUE THREAD

**Issue by rribei** [Axway-API-Management-Plus/apigateway-openlogging-elk#232]
### API-Management deployment option

OpenShift

### Question

Can we use paid versions of Filebeat, Logstash, Elastic and Kibana? Are there specific version we should use?

**Comment by NComandini** [comment]
You can bring your own ELK stack but it must be a v7 version.
You will have to deploy the memcached and the apim4elastic components.

Memcached and filebeat configuration can be extracted from this repository.
