### ISSUE TITLE
Index Domain Audit-Logs

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apigateway-openlogging-elk#26]
The solution should also index Audit-Log information into Elasticsearch and by that make it searchable.

- the retention period should be configurable by the customer
- the solution must support a retention period up to 3 years

**Comment by rekies** [comment]
Both, Admin Node Manager and API-Gateway audit logs must be consumed.
Probably different Elasticsearch indexes should be used to cater the topology admin traffic (audit log of ANM's) verus API-Manager application audit log data (audit logs coming from same API-Gateway group = one API-Manager); means we would need to be able to distinguish between the API gateway (deployment) groups.

**Comment by cwiechmann** [comment]
@rekies, To my understanding, all Domain-Audit events from ANM and API-Manager are going into the same Domain-Audit-Logs based on the configured categories:
![image](https://user-images.githubusercontent.com/16292002/94523145-12faa000-0231-11eb-9b0d-d7de13dc2c30.png)

**Comment by cwiechmann** [comment]
Domain-Audit entries are now indexed
