### ISSUE TITLE
Add support for multiple API-Gateways (Tenants, Stages, etc.)

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apigateway-openlogging-elk#38]
**User story**
The requirement is to support split information from multiple API-Gateway/API-Managers in one Elasticsearch, but have it separated from each other. 
This requires:
- Data to store in different indices using some kind of prefix/suffix, which can be configured
- API-Builder Lookup needs to connect to the correct API-Manager
  - perhaps using the domainId
- API-Builder User-Lookup needs to connect to the correct ANM & API-Manager
- Kibana Dashboards also needs some kind of variable containing the prefix/suffix
  - not sure if this is even possible

**Comment by jojo221119** [comment]
@cwiechmann How is this different to the current implementation for multiple Gateway Groups?

**Comment by cwiechmann** [comment]
The difference is to store data in Elasticsearch completely separated. When using multiple API-Gateway groups everything goes into one Elasticsearch index anyway.

**Comment by cwiechmann** [comment]
That's is actually not possible when using ILM as the index-roll-over alias must be a fixed string.
