### ISSUE TITLE
Logspector hard coded for localhost

### ISSUE THREAD

**Issue by dpecnikQualcomm** [Axway-API-Management-Plus/apigateway-openlogging-elk#4]
https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/blob/master/nginx/www/js/logspector.js#L271 

https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk/blob/c4b1cf717d1bbda178f3dc57750e2ea4bf2438b2/nginx/www/js/logspector.js#L605

Can you make this relative to the actual hostname.  We installed this on a server and this is failing with localhost.

**Comment by cwiechmann** [comment]
Thanks for reporting. Yes, that makes sense. I'll take care of this.

**Comment by cwiechmann** [comment]
@dpecnikQualcomm, we have decided to remove the separate application and instead integrate it with the standard Traffic-Monitor.
