### ISSUE TITLE
Issue with the latest Release Version 1.0.0-RC2

### ISSUE THREAD

**Issue by NNewar** [Axway-API-Management-Plus/apigateway-openlogging-elk#42]
**Axway APIM-ELK version**
APIM 7.6.2

**API-Manager Version**
APIM 7.6.2

**Expected behavior**
Installation should have been completed without any issue.

**Actual behavior**
Unable to pull the API Builder image from the docker repository.

![image](https://user-images.githubusercontent.com/71384302/93762509-5a7b9d80-fc2d-11ea-8c99-12a7f8b81b0f.png)

Current - image: cwiechmann/apibuilder4elastic:v1.0.0-RC1
Correct - image: cwiechmann/apibuilder4elastic:v1.0.0-RC2

I saw that you have the correct image definition inside the code, however, the latest release needs to be updated.

**Comment by cwiechmann** [comment]
Thanks @NNewar! You are right! I don't know how this happened, but I fixed the release as you suggested.
