### ISSUE TITLE
Allow to call ANM REST API with HTTP Basic

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apigateway-openlogging-elk#44]
**User story**
Automated tests need to call the ANM REST API to check if information is passed to the backend servers.
With the openlogging-elk, the API calls using HTTP Basic are not working.
We believe this feature request makes sense because these are normal API calls and if the automated tests need to first get a session cookie to do these API calls, it would go against the best practice of having stateless API calls.

**Additional context**
ANM API: https://apidocs.axway.com/swagger-ui/index.html?productname=apigateway&productversion=7.6.2&filename=api-gateway-swagger.json

**Comment by cwiechmann** [comment]
@remisbaima, I added support for HTTP-Basic Authorization to the Traffic-Monitor API. Now, if you provide an Authorization header, this header is send to the Admin-Node-Manager. 
Can you please have a look on your side. You can use the latest docker image to test it:
`docker pull cwiechmann/apibuilder4elastic:latest`
Let me know, if this works for you. Still at runtime, when being integrated the ANM-Session of the current user is used.

**Comment by remisbaima** [comment]
It works.
Thanks
