### ISSUE TITLE
API Builder: Issuer Certificate Missing Error

### ISSUE THREAD

**Issue by NNewar** [Axway-API-Management-Plus/apigateway-openlogging-elk#45]
**Axway APIM-ELK version**
APIM 7.6

**API-Manager Version**
APIM 7.6

**Question**
The API Gateway Manager was unable to connect with the API Builder due to the SSL Handshake Error. I have provided the complete detail below. I checked and found out, the API Builder certificate that has been provided does not have any issuer. 
So do we have to use our own certificate with the API Builder and everything else?

**What I've tried so far**
I will create a new certificate and will try if it will resolve the issue.

**Additional information**
![image](https://user-images.githubusercontent.com/71384302/94275826-13f7ad00-ff65-11ea-8f5a-b4166f576c8f.png)

**Comment by cwiechmann** [comment]
@NNewar, have you downloaded the release package or do you cloned the repository?

**Comment by NNewar** [comment]
@cwiechmann, I have used the release package.

**Comment by cwiechmann** [comment]
The Policy-XML file which is provided within the release package has the correct CA configured. It's required to update your Node-Manager configuration with the file: nodemanager/policy-use-elasticsearch-api-7.7.0.xml - This file also contains the correct CA.

**Comment by cwiechmann** [comment]
https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk#configure-the-admin-node-manager

**Comment by cwiechmann** [comment]
I made a note, that you should not use the XML-File directly from GitHub as it may contain a different certificate not being compatible from the certificates in the release package. Just to make sure.

**Comment by NNewar** [comment]
@cwiechmann Thank you for let me know about the issue. 
Yes, I copied the XML file from Github, and thank you for highlighting this point. 
I will use the configuration file that you have mentioned and will update you on the same.
