### ISSUE TITLE
Add support for Payloads based on Elasticsearch

### ISSUE THREAD

**Issue by NNewar** [Axway-API-Management-Plus/apigateway-openlogging-elk#46]
**Axway APIM-ELK version**
Latest Release

**API-Manager Version**
APIM 7.6.2

**Expected behavior**
We should be able to see the API Request payloads inside the API gateway manager.

**Actual behavior**
We are unable to see the API Request payloads inside the API Gateway Manager.
![image](https://user-images.githubusercontent.com/71384302/95062124-266aa700-071a-11eb-8865-cbab61a7579c.png)

**Test case sample**
We are currently using the ELK solution to see all the HTTP requests. All the requests do not provide any payload.

**Comment by cwiechmann** [comment]
@NNewar, serving the payload is not yet implemented by the API-Builder Traffic-Monitor-API, hence the error you see is raised by the ANM directly. Please make sure, that you don't send that kind of requests to the API-Builder project.

**Comment by cwiechmann** [comment]
@NNewar, I have started to work on this issue and realized a blocker. My initial plan was to store the payload messages, which are store by OpenTraffic into an Elasticsearch index like any other data.
![image](https://user-images.githubusercontent.com/16292002/103949688-ef05ff00-513b-11eb-9dee-b898d969b4ba.png)
For that, I wanted to use Filebeat to pick up the payload file (as a single document), send it to Logstash and store it in Elasticsearch. 

Unfortunately, that doesn't work, as Filebeat requires a supported Line-Terminator like `\n`, `\r\n`, etc.. But it is not guaranteed that sent & received payload message have a Line-Terminator in all cases. Actually, there is no workaround for that behavior based on my research. Some people use a Cron-Script to add a Line-Ending, but this is not feasible as we may have millions of file and not only a few thousands. 
That's not really a limitation of Filebeat, it is just not designed to ship complete files.

I see a few options now:

**1. A shared volume**
Customers configure a shared volume, that make the OpenTraffic-Payloads available to the API-Builder Docker-Container. 
**2. Using the Local-NM**
The Node-Manager on each API-Gateway will read the files directly from logs/payloads. When the ANM is requested to show/save a payload, it will forward the request to the local Node-Manager, which reads, using a policy, the payload directly from disk. The retention period then depends on how long each API-Gateway stores the payload files.
**3. Different shipper**
The third option is to use a different shipper, which runs in addition to Filebeat on each API-Gateway. This shipper, will pass on the payload messages into Elasticsearch.

What would your preferred option for this problem, @NNewar? 

I prefer the second option, even if it would require to change the Local-Node-Manager on each API-Gateway (but this is One-Time-Action). 
Using a CRON-Job Script the customer can decide on how long he would like to make the payload data available.

**Comment by cwiechmann** [comment]
I had a discussion with a colleague and he pointed out, that option no. 2 is not a valid option, when using EMT mode. Hence, this option is out. 
We agreed to start with option 1 and perhaps add later option 3.

**Comment by NNewar** [comment]
Hello @cwiechmann,

Option 1, here you will be storing the open-logging payload on the share volume. This option should be fine, however, the main concern would be the performance of the API Builder when it will extract the information from the server.

Option 2, apart from the issue with the EMT mode, I believe there will be an issue with the policy performance. Using policy to extract the payload from the server takes significant time when the number of files stored is high.

Option3, this is also a viable option.

Thank you for letting us know about the different approaches you will be trying to solve this issue. 👍

**Comment by cwiechmann** [comment]
Thanks for the feedback @NNewar. Loading the payload information is not an issue, as the files are stored individually, per leg and direction.
Example:
`logs/payloads/2021-01-07/09.15/8433f75fa1002ab429d7edef-0-sent`
And the reference to that file is saved the OpenTraffic-Logs, which are save in Elasticsearch. With that, it's a direct access to the payload file.

**Comment by cwiechmann** [comment]
Payload support has been added to the solution and will become available with version 2.0.0. 

See here for more details: 
https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk#traffic-payload
