### ISSUE TITLE
Other Requests uses the OPSDB

### ISSUE THREAD

**Issue by NNewar** [Axway-API-Management-Plus/apigateway-openlogging-elk#47]
**User story**
This solution provides the correct information for the HTTP Requests. However, we will still need to use the OPSDB configuration to see the other requests such as JMS.

**Additional context**
We would like to have this feature to be included with the current solution. Our customer uses the JMS requests for their EDI flows. So in order to provide them the complete solution, we would like this feature to be included in the later releases.

**Comment by cwiechmann** [comment]
@NNewar, you are right. Currently only HTTP and Filetransfer is supported. More will be added later.
