### ISSUE TITLE
Some visualizations are failing with error "[esaggs] > Bad Request"

### ISSUE THREAD

**Issue by swarii** [Axway-API-Management-Plus/apigateway-openlogging-elk#48]
**Axway APIM-ELK version**
1.0.0

**API-Manager Version**
7.7

**Expected behavior**
Visualizations render without errors

**Actual behavior**
Some visualizations are failing with error "[esaggs] > Bad Request"

**Test case sample**
Issues can be seen on the deployed instance here:
http://ec2-34-241-66-70.eu-west-1.compute.amazonaws.com:8080/
The server can be down, please let me know I'll start it

**Comment by cwiechmann** [comment]
@swarii, I cannot see the error message anymore. Now I do see: 

_Saved "field" parameter is now invalid. Please select a new field._ 

Have you changed anything?

**Comment by swarii** [comment]
@cwiechmann you're right about the new behavior but I haven't changed anything.

**Comment by swarii** [comment]
There is another problem I can see now. Some visualizations should be rendering something, but it says "no data to display"
![image](https://user-images.githubusercontent.com/63319592/98116963-11974580-1e77-11eb-8683-ac237901b73b.png)

**Comment by cwiechmann** [comment]
@swarii, As we talked offline - Do you have some updates to share?
