### ISSUE TITLE
Kibana will not start with Elasticsearch hosts variable as array

### ISSUE THREAD

**Issue by Wibrandus** [Axway-API-Management-Plus/apigateway-openlogging-elk#55]
**Axway APIM-ELK version**
7.8.1

**API-Manager Version**

**Expected behavior**
Kibana starts using environment variables. ELASTICSEARCH_HOSTS variable is used to connect to Elasticsearch cluster.
custom-entrypoint.sh script is used to format the variable so Kibana can use it.

**Actual behavior**
Kibana gives error when starting:
" FATAL  Error: [config validation of [elasticsearch].hosts]: types that failed validation:
- [config validation of [elasticsearch].hosts.0]: expected value of type [string] but got [Array].
- [config validation of [elasticsearch].hosts.1.1]: expected URI with scheme [http|https]."

Cause of error:
custom-entrypoint.sh script exports the environment variable ELASTICSEARCH_HOSTS as type Array.

**Test case sample**

**Comment by cwiechmann** [comment]
Thanks for reporting @Wibrandus. Not sure, why I have realized this before. Looks like, the Shell evaluates the variable not as expected. I have moved some of the declaration into the AWK-Part. Now it works.
