### ISSUE TITLE
Not getting logs in APIGateway manager

### ISSUE THREAD

**Issue by venkatesulua1990** [Axway-API-Management-Plus/apigateway-openlogging-elk#60]
**Axway APIM-ELK version**
Latest One as per docker images

**API-Manager Version**
Axway 20200930 version

**Question**
API Logs not coming to APIGateway Manager

**What I've tried so far**

**Additional information**
Have configure all steps but data is not loading into APIGateway Manager,when i look into apibuilder below is the one it is showing. Any help how to debug.
 Request {"method":"GET","url":"/api/elk/v1/api/router/service/5c88e5c3a9aa/ops/search?ago=24h&count=1000&field=leg&format=json&protocol=http&value=0","headers":{"host":"glchbs-ss220462.eu.novartis.net:8080","max-forwards":"19","via":"1.0 464c50cc960a (), 1.1 5c88e5c3a9aa (Gateway), 1.0 464c50cc960a ()","accept":"application/json","accept-language":"en-US,en;q=0.9","cookie":"experimentation_subject_id=IjM5N2M3ZjM5LTAzYzYtNGYyMS05NGViLWJlYzFjOWEzYmJlNCI%3D--b101d045781cf24ec1f7df36acc93c9bd4deef09; rtFa=piyMuXf7TsekuxdIMKbVmVhE/XijIFWhmedEY1m/OEImRjM1QTY5NzQtNjA3Ri00N0Q0LTgyRDctRkYzMUQ3REM1M0E1XirUJiTVGSnppKRRN5vlN6lbKfVHD15elhtAVvXdD+jnw10O7/sMATVIkUYO7IJDLXEPOLabAqM4fIvFtjCUhPyg/PJtRM7i8Rs0r4Pp+Pp7xu2U6rET75d1XjQa4VMq0Il2Oy4so0ubwuhp+Kkb2jahAFlFq7A3xPWsmow+Jq4mJd7niwiLfA1Xwc/bYq0aVBEOBFPQyFP9MM8PrZAnCnblKR4kDsvh4DrQbHYdA+Nmxe9cwcYccbz+ihK89K9MyD8OevC/zx+gp917Wqt+0pjG3cANm1lkJ5g+aEGslX7hrWFKJq6kji5zV1fMNvzQFFDnUF/wb5JATrY6S31v3kUAAAA=; portal.logintypesso=false; portal.demo=off; portal.isgridSortIgnoreCase=on; VIDUSR=1608383410-mCKkio68mnPddw%3d%3d; APIMANAGERSTATIC=697d6428-81f4-41bd-a34a-0f2e91de3744","referer":"https://glchbs-ss220460.eu.novartis.net:8090/","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-origin","user-agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36","x-requested-with":"XMLHttpRequest","connection":"keep-alive","x-correlationid":"Id-2c0cde5f49240d008f2689da 1"},"remoteAddress":"::ffff:10.166.44.49","remotePort":36784}
1608387628691  [request-id: 02241255-cc8b-4893-8332-459c63a7625f] Response {"statusCode":500,"headers":{"server":"API Builder/4.33.9","request-id":"02241255-cc8b-4893-8332-459c63a7625f","x-xss-protection":"1; mode=block","x-frame-options":"DENY","surrogate-control":"no-store","cache-control":"no-store, no-cache, must-revalidate, proxy-revalidate","pragma":"no-cache","expires":"0","x-content-type-options":"nosniff","start-time":"1608387628687","content-type":"application/json; charset=utf-8","response-time":"4","content-md5":"9cc17320d26c7b99c7d705a2596e233c","content-length":"78","etag":"W/\"4e-McghFT6g5jYA946y5FI58Q6wHuc\"","vary":"Accept-Encoding"}}

**Comment by cwiechmann** [comment]
Do you checked the troubleshooting steps: https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk#troubleshooting ?

**Comment by cwiechmann** [comment]
Hi @venkatesulua1990, have you made any progress? Please let me know, otherwise I'll close this issue.

**Comment by venkatesulua1990** [comment]
Hi ,

I am working on it still not able to figure out issue

Regards,
Venkatesulu A

**Comment by cwiechmann** [comment]
Housekeeping. Closing this issue as of now. Feel free to reopen it if needed.
