### ISSUE TITLE
Error in volume creation for apibuilder4elastic docker-compose file

### ISSUE THREAD

**Issue by elha2060** [Axway-API-Management-Plus/apigateway-openlogging-elk#65]
**Axway APIM-ELK version**
v2.0.0

**API-Manager Version**
-

**Expected behavior**
execution of "docker-compose up -d" as instructed by documentation to function and that logstash, memcached and apibuilder4elastic containers to come up.

**Actual behavior**
ERROR: for apibuilder4elastic  Cannot create container for service apibuilder4elastic: create .: volume name is too short, namesCreating memcached          ... done

ERROR: for apibuilder4elastic  Cannot create container for service apibuilder4elastic: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.

Issue can be solved by changing the following line in "docker-compose.yml"
FROM:
      - ${APIGATEWAY_PAYLOADS_FOLDER}:/var/log/payloads
TO:
      - ${APIGATEWAY_PAYLOADS_FOLDER}/:/var/log/payloads

**Comment by cwiechmann** [comment]
Hi @elha2060, can you please verify that the `.env` file is in place when running docker-compose ?

**Comment by elha2060** [comment]
Hi @cwiechmann, 

I can confirm that .env file is in place and the variables are populated. However, the variable ${APIGATEWAY_PAYLOADS_FOLDER} is not configured. Reason behind it is simple: This variable is tagged with "# Used-By: Filebeat" when running as docker-container. But we plan to run filebeat as standalone process.

**Comment by cwiechmann** [comment]
Got it. Do you plan to support payloads with the solution?

**Comment by cwiechmann** [comment]
As you have seen, the variable: `APIGATEWAY_PAYLOADS_FOLDER` is also use by the API-Builder process to have access to the payload files.

**Comment by cwiechmann** [comment]
Do you need any support / help / feedback on that issue @elha2060 ?
