### ISSUE TITLE
Adding support to handle/count Transactions

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apigateway-openlogging-elk#83]
**User story**
Today, the solution is managing API-Requests only. In the future it should also support/count Transaction that are based on several API-Requests.

An API-Transaction is based on a given `transactionId` which can be created by a [custom policy](https://github.com/Axway-API-Management-Plus/transaction-policy) and made available to the solution as a custom property in the API-Gateway event files.

**Comment by davidgeiger** [comment]
Among others, counting transactions will facilitate usage reporting, e.g., for licensing purposes. Would you really need a custom transactionId? The correlation between multiple API requests in a transaction can be derived using the respective X-CorrelationID headers.

Example flow via two gateways (e.g., an external and internal one):
Leg | Request | Response
--- | --- | ---
Client > GW1 | - | X-CorrelationID Id-aaa 0; Id-bbb 0
GW1 > GW2 | X-CorrelationID: Id-aaa 1 | X-CorrelationID: Id-bbb 0
GW2 > backend | X-CorrelationID: Id-bbb 1 | -

**Comment by cwiechmann** [comment]
@davidgeiger, Thanks for the feedback and sorry for the late response. 

We discussed this a lot internally and we came to the conclusion something like the transactionId is required. When looking at your example, for me it's not clear, that the request processed by GW2 belongs to the original request on GW1. GW1 may get in the response the correlationId from GW2, but this is for instance not exported to the OpenTraffic-File.

**Comment by cwiechmann** [comment]
Support for Transactions have been added with version 3.4.0. That means:
- if a Custom-Property named: `customMsgAtts.transactionId` is exported from a policy, it will ingested & indexed into ES
- the Transaction-ID is part of the Transformation-Job that aggregates using the given Transaction-ID using a value-count aggregation (`transactionId.value_count`)
- a very simple example visualization ([Axway] API-Transactions per month) is delivered that renders the Transaction-Value-Count into a monthly Vertical-Bar chart
- However, this visualization is not added to any of the dashboards to avoid confusion

Customers can use this transactionId in their own visualizations as they like. Everything else is prepared.

**Comment by davidgeiger** [comment]
Thanks Chris. Will look into adopting the mentioned policy to add a separate transactionId to the first request that is reused in all subsequent API requests. It appears to me this is something that the gateways should do anyway when we're talking about _correlation_, e. g., for end-to-end monitoring.

Just to clarify my example: the relevant information is the X-CorrelationID header in GW1's response to the client. This contains the correlation ids of all involved API requests. As a regular response header, it should also be available in the open traffic file. However, the aggregation in ELK would be more complex.

As a very basic alternative, it should also be possible to simply count the number of "backend-facing" requests that only have a single correlation id in the response. In my example this would count the request processed by GW2 but not the one processed by GW1.

**Comment by cwiechmann** [comment]
> It appears to me this is something that the gateways should do anyway when we're talking about correlation, e. g., for end-to-end monitoring

Yes, I do agree. But, you know, this is out of my control. Maybe they come up in the future with an improvement in that area, but I wanted to provide a solution now.

> This contains the correlation ids of all involved API requests. As a regular response header, it should also be available in the open traffic file. However, the aggregation in ELK would be more complex.

Yes, the response headers are exported into the OpenTraffic-File somehow, but not as a general field/information. That header would appear along with other headers in the Leg0-Information. And you are right, using that information would make things very complicated.

> As a very basic alternative, it should also be possible to simply count the number of "backend-facing" requests that only have a single correlation id in the response. In my example this would count the request processed by GW2 but not the one processed by GW1.

Same here, you would have to parse the response headers. Which is complex and might be costly in terms of processing time.
