### ISSUE TITLE
Disable Custom Properties

### ISSUE THREAD

**Issue by rchinthakuntla** [Axway-API-Management-Plus/apigateway-openlogging-elk#95]
**User story**
The current solution seem to be build, tested and verified against API Management 7.7.x version. 
Some of our customers are still on 7.6.2 and would like to leverage this solution.  While most of the pipelines work, 
OpenTraffic pipeline is failing to do API detail lookup. This results in some of the Kibana dashboards not work as expected. 

**Additional context**

Call from logstash to API builder fails with 404 error. Further troubleshooting revealed that APII Builder is calling the following endpoint "https://[APIMANAGER_URL]/api/portal/v1.3/config/customproperties" in API Manager 7.6.2. 

I am afraid the endpoint does not exist in 7.6.2. We might need to disable custom properties feature (in a configurable manner) to make the solution work for API Manager 7.6.2.

**Comment by cwiechmann** [comment]
Added a new optional parameter to the env-sample:
```
# ----------------------------------------------------------------------------------------------
# Option to disable custom properties. With that, custom properties are no longer looked up 
# at the API-Manager neither indexed in Elasticsearch. If set, it is of course no longer 
# possible to use these for example for a customized authorization.
# Used-By: API-Builder
# DISABLE_CUSTOM_PROPERTIES=false
```
