### ISSUE TITLE
Helm Charts

### ISSUE THREAD

**Issue by elha2060** [Axway-API-Management-Plus/apigateway-openlogging-elk#96]
Hi,

I have noticed that with commit 4f960f8aa8259c696a56cfe685879a71254c0925, helm charts were added.
But I have not seen this officially announced in the release notes.

I would like to ask how mature are these helm charts, and could we use them in our project?

Thanks.

**Comment by cwiechmann** [comment]
The HELM-Charts are not yet ready and therefore not yet released/packaged with the solution. We aim to have HELM-Charts available by the end of April.

May I ask you one question? 
Would you expect from the solution to help you stand up the Elasticsearch-Cluster or would you expect to setup Elasticsearch + Kibana with the official Elastic-HELM-Charts?

**Comment by elha2060** [comment]
Thanks for the quick feedback. 
From our point of view, there should be a How-to guide that encompasses how we can deploy the elasticsearch-based monitoring solution on kubernetes/openshift using helm charts. It is fine if some part of this guide is a link to an external source and not from Axway (assuming that any changes that is needed to those official external helms is still documented in the guide itself).
